// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/garde": {
            "post": {
                "description": "Permet d'ajouter une garde",
                "tags": [
                    "Garde"
                ],
                "summary": "ajout d'une garde",
                "responses": {
                    "201": {
                        "description": "Garde ajoutée aavec succès",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/garde/list": {
            "post": {
                "description": "Permet de renvvoyer la liste toutes les gardes disponibles en base de données",
                "tags": [
                    "Garde"
                ],
                "summary": "Liste de gardes",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/garde/{id_garde}/delete": {
            "post": {
                "description": "Permet de supprimer une garde spécifique",
                "tags": [
                    "Garde"
                ],
                "summary": "Supression de garde",
                "responses": {
                    "201": {
                        "description": "Garde supprimé avec succès",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Id non valide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/garde/{id_garde}/get": {
            "post": {
                "description": "Permet de renvoyer une garde spécifique",
                "tags": [
                    "Garde"
                ],
                "summary": "Affichage de garde",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Id non valide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/garde/{id_garde}/put": {
            "post": {
                "description": "Permet de de modifier une garde spécifique",
                "tags": [
                    "Garde"
                ],
                "summary": "Modification de garde",
                "responses": {
                    "201": {
                        "description": "Garde modifiée avec succès",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Id invalides",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Permet à un utilisateur de se connecter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Connexion utilisateur",
                "responses": {
                    "200": {
                        "description": "Connexion réussie",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Email ou mot de passe incorrect",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pharmacie": {
            "post": {
                "description": "Permet d'ajouter une pharmacie",
                "tags": [
                    "Pharmacie"
                ],
                "summary": "Ajouter une pharmacie",
                "responses": {
                    "201": {
                        "description": "Pharmacie ajoutée avec succès",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pharmacie-garde": {
            "post": {
                "description": "Permet de faire un ajouter de pharmacie et de garde en faisant un lien par Id",
                "tags": [
                    "Pharmacie-garde"
                ],
                "summary": "Ajouter pharmacie_garde",
                "responses": {
                    "201": {
                        "description": "Oppération réussie",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Erreur lors de l'ajout",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pharmacie-garde/list": {
            "post": {
                "description": "Permet de renvoyer la liste de toutes les pharmacies de gardes disponibles en base de donnée",
                "tags": [
                    "Pharmacie-garde"
                ],
                "summary": "Lister les pharmacies de garde",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pharmacie-garde/{id}/delete": {
            "post": {
                "description": "Permet de supprimer la liaison qui est entre une pharmacie et une garde sans toutefois supprimer la pharmacie ni la garde",
                "tags": [
                    "Pharmacie-garde"
                ],
                "summary": "suppression de pharmacie-garde",
                "responses": {
                    "201": {
                        "description": "Oppération réussie",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Id invalide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pharmacie/list": {
            "post": {
                "description": "Permet de renvoyer la liste de toutes pharmacies disponible en base de donnée",
                "tags": [
                    "Pharmacie"
                ],
                "summary": "Lister pharmacie",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pharmacie/{id_harmacie}/delete": {
            "post": {
                "description": "Permet de supprimer une pharmacie spécifique",
                "tags": [
                    "Pharmacie"
                ],
                "summary": "Suppression d'une pharmacie",
                "responses": {
                    "201": {
                        "description": "pharmacie supprimée avec succès",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Id invalides",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pharmacie/{id_pharmacie}/put": {
            "post": {
                "description": "Permet de modifier une pharmacie spécifique",
                "tags": [
                    "Pharmacie"
                ],
                "summary": "Modification d'une pharmacie",
                "responses": {
                    "201": {
                        "description": "Pharmacie modifiée avec succès",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Id invalides",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pharmacie/{id}/get": {
            "post": {
                "description": "Permet de renvoyer une pharmacie spécifique",
                "tags": [
                    "Pharmacie"
                ],
                "summary": "Afficher une pharmacie",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Id invalides",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "Permet de s'inscrire en remplissant les champs",
                "tags": [
                    "User"
                ],
                "summary": "Inscription d'un utilisateur",
                "responses": {
                    "201": {
                        "description": "Utilisateur créé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/list": {
            "post": {
                "description": "Permet d'afficher la liste de tous les utilisateurs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Afficher les utilisateurs",
                "responses": {}
            }
        },
        "/user/{id}": {
            "post": {
                "description": "Permet à l'administrateur de supprimer un utilisateur",
                "tags": [
                    "User"
                ],
                "summary": "Supprimer un utilisateur",
                "responses": {
                    "200": {
                        "description": "Utilisateur supprimé avec succès",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Id invalide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/{id}/get": {
            "post": {
                "description": "Permet à l'admin et le pharmacien d'afficher un utilisateur",
                "tags": [
                    "User"
                ],
                "summary": "Afficher user",
                "responses": {
                    "200": {
                        "description": "[user]",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Id invalide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/{id}/role/patch": {
            "post": {
                "description": "Permet à l'admin de modifier le rôle d'un utilisateur",
                "tags": [
                    "User"
                ],
                "summary": "Modifier le rôle",
                "responses": {
                    "200": {
                        "description": "Rôle modifié avec succès",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Pharmacie API",
	Description:      "API de gestion des pharmacies, gardes et utilisateurs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
